---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.serviceName }}
  namespace: default
  labels:
    backstage.io/kubernetes-id: ${{ values.serviceName }}
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ${{ values.serviceName }}
  template:
    metadata:
      labels:
        app: ${{ values.serviceName }}
        backstage.io/kubernetes-id: ${{ values.serviceName }}
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: ${{ values.serviceName }}
        ports:
        - containerPort: 80
