---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: knauf-com-platform
  description: Knauf.com - Platform Team
spec:
  type: business_unit
  profile:
    displayName: Knauf.com - Platform Team
  parent: cst
  children: [content-management, operations, platform-1, platform-2, product-owner]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: products-systems
  description: Products & Systems
spec:
  type: business_unit
  profile:
    displayName: Products & Systems
  parent: cst
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: construction-software
  description: Construction Software
spec:
  type: business_unit
  profile:
    displayName: Construction Software
  parent: cst
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
  description: Guests
spec:
  type: team
  profile:
    displayName: Guests
  parent: cst
  children: []
