---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app-with-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/smajlovic-info/node-app-with-argocd.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
