---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: cms-frontend-api
spec:
  type: rest
  lifecycle: production
  owner: content-management
  system: cms
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Site Structure API
    servers:
      - url: http://knauf.com/api/
    paths:
      /sitestructure:
        post:
          summary: Create Site Structure Cache
    ...
